<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>HAL9000VoiceHelper</AssemblyName>
    <RootNamespace>HAL9000VoiceHelper</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NoWarn>$(NoWarn);NU1900</NoWarn>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Speech">
      <HintPath>$(WINDIR)\Microsoft.NET\Framework\v4.0.30319\WPF\System.Speech.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
